name       : xinput
version    : 1.6.3
release    : 6
source     :
    - http://xorg.freedesktop.org/releases/individual/app/xinput-1.6.3.tar.gz : 9f29f9bfe387c5a3d582f9edc8c5a753510ecc6fdfb154c03b5cea5975b10ce4
license    : MIT
component  : xorg.apps
summary    : xinput
description: |
    X.Org Applications - xinput
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(inputproto)
    - pkgconfig(xrandr)
    - pkgconfig(xinerama)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
