name        : xinput
version     : 1.6.2
release     : 3
source     :
    - http://xorg.freedesktop.org/releases/individual/app/xinput-1.6.2.tar.gz : 2c8ca5ff2a8703cb7d898629a4311db720dbd30d0c162bfe37f18849a727bd42
license     :
    - MIT
summary     : xinput
builddeps   :
    - pkgconfig(x11)
    - pkgconfig(xext)
    - pkgconfig(xi)
    - pkgconfig(inputproto)
    - pkgconfig(xrandr)
    - pkgconfig(xinerama)
description : |
    X.Org Applications - xinput
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
